import { writable } from "svelte/store"
import type { ChatMessage } from "./chat.types"

export const chatMessages = writable({
	1: [
		{
			id: 1,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 2,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 3,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 4,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  fdewf wwdwfdwefdw fbfgfg sdss fmessage",
			sent_by_user: false,
		},
		{
			id: 5,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 6,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 7,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 8,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 9,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  fdewf wwdwfdwefdw fbfgfg sdss fmessage",
			sent_by_user: false,
		},
		{
			id: 10,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 11,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 12,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 13,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 14,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  fdewf wwdwfdwefdw fbfgfg sdss fmessage",
			sent_by_user: false,
		},
		{
			id: 15,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 16,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "testsas  rwf rgfwdsdss wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 17,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 18,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 19,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 20,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 21,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 22,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 23,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 24,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  fdewf wwdwfdwefdw fbfgfg sdss fmessage",
			sent_by_user: false,
		},
		{
			id: 25,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 26,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "testsas  rwf rgfwdsdss wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 27,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 28,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 29,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 30,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 31,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 32,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 33,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 34,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  fdewf wwdwfdwefdw fbfgfg sdss fmessage",
			sent_by_user: false,
		},
		{
			id: 35,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 36,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "testsas  rwf rgfwdsdss wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
		{
			id: 37,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsda fdsaf dfd fagddffagfrg w ed qwd message",
			sent_by_user: false,
		},
		{
			id: 38,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test dsadsa fa message",
			sent_by_user: false,
		},
		{
			id: 39,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test s sagfdf ddsdsf message",
			sent_by_user: false,
		},
		{
			id: 40,
			name: "avoid",
			platform: "playfab",
			player_id: "playerid",
			message: "test  rwf rgfwds wfdd gdfwfd wfewdfd fw",
			sent_by_user: false,
		},
	],
} as { [key: number]: ChatMessage[] })

export function addChatMessage(serverID: number, msg: ChatMessage) {
	chatMessages.update((current) => {
		current[serverID].push(msg)
		return current
	})
}
